mavenai_project_working/mavenai_project_working/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.login),
    path('',include('users.urls')),
    path('accounts/',include('allauth.urls')),
    path('accounts/profile/',views.dashboard),
    path('accounts/google/login/callback/dashboard/',views.dashboard)
    # path('s3direct/', include('s3direct.urls')),
]

users/urls.py
from django.urls import path
from django.views.generic.base import RedirectView

from . import views

urlpatterns=[path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    path('dashboard/',views.dashboard,name='dashboard'),
    ]

mavenai_project_working/users/models.py
from django.db import models

# Create your models here.
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.urls import reverse
from json import JSONEncoder
from django.core.validators import ValidationError, RegexValidator
import re

def validate_name(value):
    pattern = re.compile("[a-zA-Z][a-zA-Z \.]+[a-zA-Z]$")
    if pattern.match(value):
        return value
    else:
        raise ValidationError('Must have only characters or space or period')
	


class RegisterUser(models.Model):
    user_name = models.CharField(max_length=100,  validators=[
        RegexValidator(
            regex='^[a-zA-Z][a-zA-Z \.]+[a-zA-Z]$',
            message='Username must not conatain numbers or characters',
            code='invalid_username'
        ),
    ])
    user_mobile_no = models.CharField(max_length=40,validators=[
        RegexValidator(
            regex='^[0-9]+$',
            message='Mobile number must  conatain only numbers',
            code='invalid_mobileno'
        ),
    ])
    user_passport_no = models.CharField(max_length=40)
    user_dob = models.DateField(blank=True, null=True)
    user_age = models.IntegerField(blank=True, null=True)
    user_email = models.CharField(max_length=50, blank=True, null=True)
    user_password = models.CharField(max_length=100, blank=True, null=True)
    user_image = models.ImageField( blank=True)

class RegiseterUserEncoder(JSONEncoder):
        def default(self, o):
            return o.__dict__

mavenai_project_working/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.core.validators import ValidationError, RegexValidator


class SignUpForm(forms.Form):
    full_name = forms.CharField(max_length=32,validators=[
        RegexValidator(
            regex='^[a-zA-Z][a-zA-Z \.]+[a-zA-Z]$',
            message='Username must not conatain numbers or characters',
            code='invalid_username'
        ),
    ])
    mobile_no = forms.CharField(max_length=10,min_length=10,validators=[
        RegexValidator(
            regex='^[0-9]+$',
            message='Mobile number must  conatain only numbers',
            code='invalid_mobileno'
        ),
    ])
    image = forms.ImageField()
    passport_num = forms.CharField()
    dob=forms.DateField
    email=forms.EmailInput
    age = forms.IntegerField(min_value=16)
  
class LoginForm(forms.Form):
    user_name = forms.CharField()
    password = forms.PasswordInput()

mavenai_project_working/users/templates/users/login.html
{% load crispy_forms_tags %}
{% load socialaccount %}

{% block content %}
    <div class="content-section" style="text-align: center">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Login Now</legend>
                {{ form|crispy }}
                <div >
                    <label for="id_password" class="control-label  requiredField">
                        Password<span class="asteriskField">*</span> </label> 
                        <div class="controls "> <input type="password" name="password" class="form-control" required="" id="id_password"> </div> 
                </div>
            </fieldset>            
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
<div class="socialaccount_ballot">
<p><a href="{% provider_login_url 'google' %}">Log In with Gmail</a></p>
  <div class="login-or">or</div>
</div>
            <div class="div">
                {{message}}
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Don't Have An Account? <a class="ml-2" href="http://127.0.0.1:8000/register">Register</a>
            </small>
        </div>
    </div>
{% endblock content %}

mavenai_project_working/users/templates/users/register.html
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group" >
                <legend class="border-bottom mb-4">Join Today</legend>
                <div >
                    <label for="id_email" class="control-label  requiredField">
                        Email<span class="asteriskField">*</span> </label> 
                        <div class="controls "> <input type="email" name="email" class="form-control" required="" id="id_email"> </div> 
                </div>
                {{ form|crispy }}
                <div >
                    <label for="id_dob" class="control-label  requiredField">
                        Date of Birth<span class="asteriskField">*</span> </label> 
                        <div class="controls "> <input type="date" name="dob" class="form-control" required="" id="id_dob"> </div> 
                </div>
            </fieldset>
            
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
            <div class="div" >
                   {{password}}
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="http://127.0.0.1:8000/login">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}